import type { Metadata } from "next";
import { Inter, Chakra_Petch } from "next/font/google"; 

import "./globals.css";
import { Navbar } from "@/components/Menu";
import { notFound } from 'next/navigation';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { routing } from '@/i18n/routing';

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const chakraPetch = Chakra_Petch({
  variable: "--font-chakra-petch",
  weight: ['300', '400', '500', '700'],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pressing CAT",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode
  params: any
}) {
  const { locale } = await params;
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }
  const messages = await getMessages();
  return (
    <html lang={locale} className={`${inter.variable} ${chakraPetch.variable} h-full`}>
      <body className="h-full bg-primary-100">
        <NextIntlClientProvider messages={messages}>
          <Navbar></Navbar>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
